import { Imovel } from '../types';

export const MOCK_IMOVEIS: Imovel[] = [
  {
    id: '1',
    tipo: 'terreno',
    titulo: 'Terreno 500m² - Jardim América',
    descricao: 'Excelente terreno plano, pronto para construir. Localização privilegiada no Jardim América, próximo a escolas e comércio.',
    valor: 95000,
    status: 'disponivel',
    localizacao: {
      latitude: -16.6950,
      longitude: -49.2580,
      bairro: 'Jardim América',
      cidade: 'Goiânia',
      estado: 'GO',
    },
    caracteristicas: {
      area_total: 500,
    },
    midias: [
      { id: '1', url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800', tipo: 'imagem', principal: true },
      { id: '1b', url: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800', tipo: 'imagem' },
    ],
    anunciante: {
      tipo: 'corretor',
      corretor: {
        id: '1',
        nome: 'João Silva',
        creci: '12345-GO',
        whatsapp: '62999998888',
      },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    tipo: 'casa',
    titulo: 'Casa 3 Quartos - Setor Bueno',
    descricao: 'Linda casa com 3 quartos sendo 1 suíte, sala ampla, cozinha americana, área de lazer com churrasqueira. Condomínio fechado com segurança 24 horas.',
    valor: 450000,
    status: 'disponivel',
    localizacao: {
      latitude: -16.7100,
      longitude: -49.2650,
      bairro: 'Setor Bueno',
      cidade: 'Goiânia',
      estado: 'GO',
    },
    caracteristicas: {
      area_total: 300,
      area_construida: 180,
      quartos: 3,
      suites: 1,
      banheiros: 2,
      vagas_garagem: 2,
      churrasqueira: true,
    },
    midias: [
      { id: '2', url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800', tipo: 'imagem', principal: true },
      { id: '2b', url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800', tipo: 'imagem' },
      { id: '2c', url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800', tipo: 'imagem' },
    ],
    tour_virtual_url: 'https://kuula.co/share/collection/7lZqZ?logo=1&info=1&fs=1&vr=0&zoom=1&autorotate=0.3&thumbs=1',
    anunciante: {
      tipo: 'imobiliaria',
      imobiliaria: {
        id: '1',
        nome: 'Imobiliária Central',
        creci: '5678-J-GO',
        whatsapp: '62988887777',
      },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    tipo: 'apartamento',
    titulo: 'Apartamento 2 Quartos - Marista',
    descricao: 'Apartamento moderno com 2 quartos, varanda gourmet, academia e piscina no condomínio. Vista privilegiada para o parque.',
    valor: 380000,
    status: 'disponivel',
    localizacao: {
      latitude: -16.7000,
      longitude: -49.2550,
      bairro: 'Setor Marista',
      cidade: 'Goiânia',
      estado: 'GO',
    },
    caracteristicas: {
      area_total: 75,
      area_construida: 75,
      quartos: 2,
      suites: 1,
      banheiros: 2,
      vagas_garagem: 1,
      academia: true,
      piscina: true,
    },
    midias: [
      { id: '3', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800', tipo: 'imagem', principal: true },
      { id: '3b', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', tipo: 'imagem' },
    ],
    tour_virtual_url: 'https://kuula.co/share/collection/7YzKx?logo=1&info=1&fs=1&vr=0&zoom=1&autorotate=0.3&thumbs=1',
    anunciante: {
      tipo: 'corretor',
      corretor: {
        id: '2',
        nome: 'Maria Santos',
        creci: '54321-GO',
        whatsapp: '62977776666',
      },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    tipo: 'terreno',
    titulo: 'Terreno 360m² - Jardim América',
    descricao: 'Terreno em ótima localização no Jardim América, documentação ok, pronto para construir. Próximo a comércios e escolas.',
    valor: 78000,
    status: 'disponivel',
    localizacao: {
      latitude: -16.6920,
      longitude: -49.2610,
      bairro: 'Jardim América',
      cidade: 'Goiânia',
      estado: 'GO',
    },
    caracteristicas: {
      area_total: 360,
    },
    midias: [
      { id: '4', url: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800', tipo: 'imagem', principal: true },
    ],
    anunciante: {
      tipo: 'corretor',
      corretor: {
        id: '1',
        nome: 'João Silva',
        creci: '12345-GO',
        whatsapp: '62999998888',
      },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    tipo: 'casa',
    titulo: 'Casa de Luxo 4 Suítes - Alphaville',
    descricao: 'Mansão espetacular em condomínio de alto padrão. 4 suítes com closet, piscina aquecida, cinema, adega climatizada e garagem para 6 carros.',
    valor: 2500000,
    status: 'disponivel',
    localizacao: {
      latitude: -16.7200,
      longitude: -49.2400,
      bairro: 'Alphaville Flamboyant',
      cidade: 'Goiânia',
      estado: 'GO',
    },
    caracteristicas: {
      area_total: 800,
      area_construida: 450,
      quartos: 4,
      suites: 4,
      banheiros: 6,
      vagas_garagem: 6,
      piscina: true,
      churrasqueira: true,
      jardim: true,
      ar_condicionado: true,
      portaria_24h: true,
    },
    midias: [
      { id: '5', url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800', tipo: 'imagem', principal: true },
      { id: '5b', url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800', tipo: 'imagem' },
      { id: '5c', url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800', tipo: 'imagem' },
    ],
    tour_virtual_url: 'https://kuula.co/share/collection/7DYjP?fs=1&vr=1&zoom=1&autorotate=0.09&thumbs=1',
    anunciante: {
      tipo: 'imobiliaria',
      imobiliaria: {
        id: '2',
        nome: 'Luxury Imóveis',
        creci: '9999-J-GO',
        whatsapp: '62999991111',
        email: 'contato@luxuryimoveis.com.br',
      },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    tipo: 'apartamento',
    titulo: 'Cobertura Duplex - Setor Oeste',
    descricao: 'Cobertura duplex com vista panorâmica da cidade. Terraço gourmet com piscina privativa, 3 suítes e acabamento de primeira linha.',
    valor: 1200000,
    status: 'negociacao',
    localizacao: {
      latitude: -16.6800,
      longitude: -49.2700,
      bairro: 'Setor Oeste',
      cidade: 'Goiânia',
      estado: 'GO',
    },
    caracteristicas: {
      area_total: 280,
      area_construida: 280,
      quartos: 3,
      suites: 3,
      banheiros: 4,
      vagas_garagem: 3,
      piscina: true,
      churrasqueira: true,
      ar_condicionado: true,
      elevador: true,
    },
    midias: [
      { id: '6', url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800', tipo: 'imagem', principal: true },
      { id: '6b', url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800', tipo: 'imagem' },
    ],
    tour_virtual_url: 'https://kuula.co/share/collection/7lZqZ?logo=1&info=1&fs=1&vr=0&zoom=1&autorotate=0.3&thumbs=1',
    anunciante: {
      tipo: 'corretor',
      corretor: {
        id: '3',
        nome: 'Carlos Mendes',
        creci: '67890-GO',
        whatsapp: '62988884444',
        foto_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200',
      },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
